name: Build Singularity SIF from Dockerfile

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build-singularity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Apptainer (Singularity) 
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt-get update
          sudo apt-get install -y apptainer

      - name: Build Docker image
        run: |
          docker build -t myimage:latest .

      - name: Convert Docker image to Singularity (.sif)
        run: |
          apptainer build myimage.sif docker-daemon://myimage:latest

      - name: Upload .sif artifact
        uses: actions/upload-artifact@v4
        with:
          name: myimage.sif
          path: myimage.sif
